### ISSUE TITLE
I am using same efi but i have restart issue

### ISSUE THREAD

**Issue by rabbicit** [fusion-pc/hackintosh-efi-big-sur-h510m#2]
Hi, I have h510m pro Motherboard, Treansend 256GB NVME M.2 SSD, Crosair 8GB Ram, Intel I3-10100.
I do not have any graphics card, I am using this Efi. With both efi always restart after boot.

**Comment by DanXus-Lzp** [comment]
Open config.plist in your EFI file, and copy the code below at DeviceProperties -> Add ，
        \<key>PciRoot(0x0)/Pci(0x2,0x0)\</key>
        \<dict>
            \<key>AAPL,ig-platform-id\</key>
            \<data>AACbPg==\</data>
        \</dict>

**Comment by rabbicit** [comment]
Thanks, I Tried with this but its same continuously restarting Computer. Its different motherboard i think, My one is MSI H510M - Pro and your one is MSI h510M - A - Pro. That's why can be some different?

**Comment by DanXus-Lzp** [comment]
MSI H510M PRO was same as MSI H510M-A PRO,Which step have you completed？have you set up your smbios info?
It's normal to restart the system several times during installation.

**Comment by DanXus-Lzp** [comment]
MSI H510M PRO was same as MSI H510M-A PRO,Which step have you completed？have you set up your smbios info?
It's normal to restart the system several times during installation.

**Comment by rabbicit** [comment]
Thanks for you response. I added normal graphics code now i see another error. https://prnt.sc/1c233rb
Something AppleUSBXHCI error with input devices. I am only using mouse keyboard and etharnet with my PC.
Not understanding how to solve it. Can you suggest something?

**Comment by DanXus-Lzp** [comment]
0.7.0 EFI USB map was real USB map for H510M-A PRO, so you can try 0.6.8 EFI. remember add normal graphics code.

**Comment by rabbicit** [comment]
Thanks, I will try again with 0.6.8 EFI.
