### ISSUE TITLE
is:issue is:open i3-10100核显、微星H510M A PRO，核显可否驱动

### ISSUE THREAD

**Issue by lucianLF** [fusion-pc/hackintosh-efi-big-sur-h510m#3]
is:issue is:open i3-10100核显、微星H510M A PRO，核显可否驱动
i3-1010f驱动链接：
https://github.com/fusion-pc/hackintosh-efi-big-sur-h510m/blob/main/README.md

**Comment by DanXus-Lzp** [comment]
需要添加代码在 DeviceProperties -> Add ，
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
<dict>
<key>AAPL,ig-platform-id</key>
<data>AACbPg==</data>
</dict>
